title: Training Self-Driving Cars Faster in Godot Game Engine
description: Leveraging Behavior Cloning to Accelerate Proximal Policy Optimization for Self-Driving Car Learning
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman